---
title: "Quick look at 4 reps"
output: html_notebook
---

Just need to grab the gathered ROC curves for MUP from the Snakemake output
file and then give them a quick plot:
```{r}
library(tidyverse)

#x <- read_rds("results/summarized/all-rocs.rds") %>%
x <- read_rds("stored-results/manually-gathered-rocs.rds") %>%  
  mutate(miss_rate = factor(var_miss_rate))

# summarize the different conditions, etc.
x %>%
  count(scenario, cohort_inclusion, miss_rate, rep, remainder) %>% View()

# we need to name these better
x2 <- x %>%
  mutate(
    full_sib_treatment = ifelse(is.na(full_sib_treatment), "none", full_sib_treatment),
    descriptor = case_match(
      remainder,
      "exclude_same_cohort-both_diag_and_var-rocresults.rds" ~ "sequoia-diag-and-var",
      "exclude_same_cohort-only_var-rocresults.rds" ~ "sequoia-only-var",
      "hot_both_diag_and_var_rocs.rds" ~ "HOT-diag-and-var",
      "hot_only_var_rocs.rds" ~ "HOT-only-var",
      "mup_rocs.rds" ~ "MUP"
    ),
    descriptor = str_c(descriptor, full_sib_treatment, sep = "---")
  )
```


Plot them all.
```{r}
g <- x2 %>%
  ggplot(aes(x = fpr, y = tpr, colour = descriptor, group = interaction(descriptor, rep))) +
  facet_grid(miss_rate ~ scenario + cohort_inclusion) +
  geom_line() +
  scale_colour_brewer(type = "qual", palette = "Set1")

g
```


```{r}
dir.create("outputs/003", recursive = TRUE, showWarnings = FALSE)
ggsave("outputs/003/all-reps-with-HOT-and-Sequoia-and-MUP-full-sib-treatment.pdf", width = 15, height = 10)
```


**THE STUFF BELOW HERE HAS NOT BEEN UPDATED NOW THAT HOT HAS BEEN ADDED**

Let's have a look at one case and color by relationship.
```{r}
one_run <- x %>%
  filter(rep == 1, scenario == "nonWF_simple", cohort_inclusion == "exclude_same_cohort", miss_rate == 0.15) %>%
  mutate(relat = str_c(dom_relat, max_hit, sep = "-"))
```

Then plot that thing:
```{r}
ggplot(one_run, aes(x = fpr, y = tpr, colour = relat)) +
  geom_point(size = 0.3)

dir.create("outputs/003", recursive = TRUE, showWarnings = FALSE)
ggsave("outputs/003/relationships-wrong.pdf", width = 20, height = 20)
```
That is pretty cool.

Let's make another one, drawn by admixture fraction.
```{r}
ggplot(one_run, aes(x = fpr, y = tpr, colour = kid_q1)) +
  geom_point(size = 0.3) +
  scale_colour_viridis_c()

dir.create("outputs/003", recursive = TRUE, showWarnings = FALSE)
ggsave("outputs/003/colored-by-admix-fracts.pdf", width = 20, height = 20)
```
