# path to tabular configuration
sim_spec: "config/sim_spec.csv"


# slim and marker simulation scenarios
sim_scenarios:
  cyclone_WF:
    slim_base: config/slim_templates/WF_model.slim
    var_freqs: config/var_freqs/cyclone-var-freqs.rds
    diag_markers: config/diag_markers/wct-rbt-yct-spp-diag-markers.rds
  cyclone_nonWF:
    slim_base: config/slim_templates/nonWF_model.slim
    var_freqs: config/var_freqs/cyclone-var-freqs.rds
    diag_markers: config/diag_markers/wct-rbt-yct-spp-diag-markers.rds


