# path to tabular configuration
sim_spec: "config/simulation_specifications.csv"


# slim and marker simulation scenarios
sim_scenarios:
  WF_simple:
    slim_base: config/slim_templates/WF_model.slim
    var_freqs: config/var_freqs/langford-var-freqs.rds
    diag_markers: config/diag_markers/wct-rbt-yct-spp-diag-markers.rds
  nonWF_simple:
    slim_base: config/slim_templates/nonWF_model.slim
    var_freqs: config/var_freqs/langford-var-freqs.rds
    diag_markers: config/diag_markers/wct-rbt-yct-spp-diag-markers.rds


